# Generated by Django 4.2.23 on 2025-07-31 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NauUserExtendedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_authorization', models.BooleanField(verbose_name="I have read and understood the <a href='https://www.nau.edu.pt/legal/politica-de-privacidade/' rel='noopener' target='_blank'>Privacy Policy</a>")),
                ('full_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Full name')),
                ('bio', models.TextField(blank=True, help_text='Tell us a bit about yourself.', verbose_name='Biography')),
                ('wants_newsletter', models.BooleanField(default=False, verbose_name='Subscribe to newsletter')),
                ('favorite_language', models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('go', 'Go')], max_length=50, verbose_name='Favorite programming language')),
                ('password_hint', models.CharField(blank=True, help_text='Optional hint to remember your password.', max_length=255, verbose_name='Password hint')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='I accept the Terms and Conditions.')),
                ('registration_token', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Registration token (internal)')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra Info',
                'verbose_name_plural': 'Extra Info entries',
            },
        ),
    ]
