# Generated by Django 4.2.23 on 2025-07-31 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nauuserextendedmodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='nauuserextendedmodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nickname'),
        ),
    ]
